//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Histories = new HashSet<History>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Contakts { get; set; }
        public string Birthday { get; set; }
        public string Notes { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }
    }
}
