//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHistory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string ServiceName { get; set; }
        public string Cost { get; set; }
        public int EmployeeTableId { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
