//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public EmployeeTable()
        {
            this.Shedules = new HashSet<Shedule>();
            this.EmployeeHistories = new HashSet<EmployeeHistory>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Post { get; set; }
        public string Birthday { get; set; }
        public string Contacts { get; set; }
        public string PersonalData { get; set; }
        public string Salary { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<Shedule> Shedules { get; set; }
        public virtual ICollection<EmployeeHistory> EmployeeHistories { get; set; }
    }
}
