//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.TypeOfServices = new HashSet<TypeOfService>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Post { get; set; }
        public string Birthday { get; set; }
        public string Contacts { get; set; }
        public string PersonalData { get; set; }
        public string Salary { get; set; }
    
        public virtual ICollection<TypeOfService> TypeOfServices { get; set; }
    }
}
