//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int Id { get; set; }
        public string GoodName { get; set; }
        public string GoodPrice { get; set; }
        public int TypeOfGoodsId { get; set; }
        public string Count { get; set; }
    
        public virtual TypeOfGoods TypeOfGood { get; set; }
    }
}
