//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodHistory
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public string Price { get; set; }
        public string GoodName { get; set; }
        public string Customer { get; set; }
    }
}
