//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiMei.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeiMeiContext : DbContext
    {
        public MeiMeiContext()
            : base("name=MeiMeiContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TypeOfService> TypeOfServices { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<EmployeeTable> EmployeeTables { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<History> Histories { get; set; }
        public DbSet<TypeOfGoods> TypeOfGoods { get; set; }
        public DbSet<Goods> Goods { get; set; }
        public DbSet<Shedule> Shedules { get; set; }
        public DbSet<SheduleTime> SheduleTimes { get; set; }
        public DbSet<SheduleColumn> SheduleColumns { get; set; }
        public DbSet<GoodHistory> GoodHistories { get; set; }
        public DbSet<EmployeeHistory> EmployeeHistories { get; set; }
    }
}
