//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfGoods
    {
        public TypeOfGoods()
        {
            this.Goods = new HashSet<Goods>();
        }
    
        public int Id { get; set; }
        public string TypeGoods { get; set; }
    
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
