//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiMei.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeiMei.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_btn {
            get {
                return ResourceManager.GetString("Add_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add type of goods.
        /// </summary>
        public static string AddGoodWind_AddTypeOfGood_text {
            get {
                return ResourceManager.GetString("AddGoodWind_AddTypeOfGood_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of goods.
        /// </summary>
        public static string AddGoodWind_TypeOfGood_text {
            get {
                return ResourceManager.GetString("AddGoodWind_TypeOfGood_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a employee.
        /// </summary>
        public static string AddingEmployee_Title {
            get {
                return ResourceManager.GetString("AddingEmployee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a goods.
        /// </summary>
        public static string AddingGoods_Title {
            get {
                return ResourceManager.GetString("AddingGoods_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a schedule.
        /// </summary>
        public static string AddingSchedule_title {
            get {
                return ResourceManager.GetString("AddingSchedule_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a services.
        /// </summary>
        public static string AddingServices_title {
            get {
                return ResourceManager.GetString("AddingServices_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a client.
        /// </summary>
        public static string AddingСlient_Title {
            get {
                return ResourceManager.GetString("AddingСlient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additionally.
        /// </summary>
        public static string Additionally_text {
            get {
                return ResourceManager.GetString("Additionally_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string AddPhoto_text_btn {
            get {
                return ResourceManager.GetString("AddPhoto_text_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply_btn {
            get {
                return ResourceManager.GetString("Apply_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention_message {
            get {
                return ResourceManager.GetString("Attention_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category services.
        /// </summary>
        public static string CategoryServices_text {
            get {
                return ResourceManager.GetString("CategoryServices_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create_btn {
            get {
                return ResourceManager.GetString("Create_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer_text {
            get {
                return ResourceManager.GetString("Customer_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string CustomerWind_text_addInfo {
            get {
                return ResourceManager.GetString("CustomerWind_text_addInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information :.
        /// </summary>
        public static string CustomerWind_text_Info {
            get {
                return ResourceManager.GetString("CustomerWind_text_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data_text {
            get {
                return ResourceManager.GetString("Data_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_btn {
            get {
                return ResourceManager.GetString("Delete_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_btn {
            get {
                return ResourceManager.GetString("Edit_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a customrs.
        /// </summary>
        public static string EditingClient_title {
            get {
                return ResourceManager.GetString("EditingClient_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a emplouee.
        /// </summary>
        public static string EditingEmployee_title {
            get {
                return ResourceManager.GetString("EditingEmployee_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing services.
        /// </summary>
        public static string EditingServices_text {
            get {
                return ResourceManager.GetString("EditingServices_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change photo.
        /// </summary>
        public static string EditPhoto_btn {
            get {
                return ResourceManager.GetString("EditPhoto_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string EditProduct_text {
            get {
                return ResourceManager.GetString("EditProduct_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string EmployeeWind_text_Birthday {
            get {
                return ResourceManager.GetString("EmployeeWind_text_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string EmployeeWind_text_Contacts {
            get {
                return ResourceManager.GetString("EmployeeWind_text_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string EmployeeWind_text_FullName {
            get {
                return ResourceManager.GetString("EmployeeWind_text_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string EmployeeWind_text_Function {
            get {
                return ResourceManager.GetString("EmployeeWind_text_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about employee.
        /// </summary>
        public static string EmployeeWind_text_Info {
            get {
                return ResourceManager.GetString("EmployeeWind_text_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport details :.
        /// </summary>
        public static string EmployeeWind_text_PassportDetails {
            get {
                return ResourceManager.GetString("EmployeeWind_text_PassportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone :.
        /// </summary>
        public static string EmployeeWind_text_Phone {
            get {
                return ResourceManager.GetString("EmployeeWind_text_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First you fill in all fields.
        /// </summary>
        public static string FirstFill_message {
            get {
                return ResourceManager.GetString("FirstFill_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, select the object.
        /// </summary>
        public static string FirstSelectObject_message {
            get {
                return ResourceManager.GetString("FirstSelectObject_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From_txt {
            get {
                return ResourceManager.GetString("From_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string MainWind_btn_Customer {
            get {
                return ResourceManager.GetString("MainWind_btn_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string MainWind_btn_Employee {
            get {
                return ResourceManager.GetString("MainWind_btn_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        public static string MainWind_btn_Goods {
            get {
                return ResourceManager.GetString("MainWind_btn_Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string MainWind_btn_Service {
            get {
                return ResourceManager.GetString("MainWind_btn_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string MainWind_btn_Shedule {
            get {
                return ResourceManager.GetString("MainWind_btn_Shedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer_text {
            get {
                return ResourceManager.GetString("Manufacturer_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of goods.
        /// </summary>
        public static string NameOfGood_text {
            get {
                return ResourceManager.GetString("NameOfGood_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of service.
        /// </summary>
        public static string NameOfService_text {
            get {
                return ResourceManager.GetString("NameOfService_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NameOfServices_text {
            get {
                return ResourceManager.GetString("NameOfServices_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string NumberGoods_text {
            get {
                return ResourceManager.GetString("NumberGoods_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of goods.
        /// </summary>
        public static string PriceOfGood_text {
            get {
                return ResourceManager.GetString("PriceOfGood_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of service.
        /// </summary>
        public static string PriceOfService_text {
            get {
                return ResourceManager.GetString("PriceOfService_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сost.
        /// </summary>
        public static string PriceOfServices_text {
            get {
                return ResourceManager.GetString("PriceOfServices_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed successfully .
        /// </summary>
        public static string RemovedSuccessfully_message {
            get {
                return ResourceManager.GetString("RemovedSuccessfully_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successfully.
        /// </summary>
        public static string Save_message {
            get {
                return ResourceManager.GetString("Save_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the service type.
        /// </summary>
        public static string SelectServiceType_message {
            get {
                return ResourceManager.GetString("SelectServiceType_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Sell_btn_text {
            get {
                return ResourceManager.GetString("Sell_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_btn {
            get {
                return ResourceManager.GetString("Settings_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add place.
        /// </summary>
        public static string SettingsWind_AddPlace_text {
            get {
                return ResourceManager.GetString("SettingsWind_AddPlace_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of the day.
        /// </summary>
        public static string SettingsWind_EndDay {
            get {
                return ResourceManager.GetString("SettingsWind_EndDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a place.
        /// </summary>
        public static string SettingsWind_Place_text {
            get {
                return ResourceManager.GetString("SettingsWind_Place_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The beginning of the day.
        /// </summary>
        public static string SettingsWind_StartDay {
            get {
                return ResourceManager.GetString("SettingsWind_StartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, enter the start and end of the working day.
        /// </summary>
        public static string StartEnterDay_message {
            get {
                return ResourceManager.GetString("StartEnterDay_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time_txt {
            get {
                return ResourceManager.GetString("Time_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To_txt {
            get {
                return ResourceManager.GetString("To_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add type of service.
        /// </summary>
        public static string TypeService_add_text {
            get {
                return ResourceManager.GetString("TypeService_add_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of service.
        /// </summary>
        public static string TypeService_text {
            get {
                return ResourceManager.GetString("TypeService_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сompleted.
        /// </summary>
        public static string Сompleted_message {
            get {
                return ResourceManager.GetString("Сompleted_message", resourceCulture);
            }
        }
    }
}
